spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    username: root
    password: 26622662
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # prevents Hibernate from changing the schema
    show-sql: true      # optional: shows SQL statements in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081
